-- Migration 005: Insurance / Document RAG
-- Adds document storage table for retrieval-augmented generation.
-- Embeddings are auto-generated by the existing `embed` Edge Function
-- via a database webhook (same pattern as messages and memory tables).

-- ============================================================
-- DOCUMENTS TABLE (RAG Document Chunks)
-- ============================================================
CREATE TABLE IF NOT EXISTS documents (
  id          UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  title       TEXT        NOT NULL,           -- document / policy name
  source      TEXT        NOT NULL,           -- original filename
  chunk_index INTEGER     NOT NULL DEFAULT 0, -- position within document
  content     TEXT        NOT NULL,           -- chunk text (~500 tokens)
  embedding   VECTOR(1536),                   -- auto-populated by embed webhook
  metadata    JSONB       DEFAULT '{}'        -- page, section, tags, etc.
);

CREATE INDEX IF NOT EXISTS idx_documents_title   ON documents(title);
CREATE INDEX IF NOT EXISTS idx_documents_source  ON documents(source);

-- RLS
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for service role" ON documents FOR ALL USING (true);

-- ============================================================
-- SEMANTIC SEARCH FUNCTION
-- ============================================================
CREATE OR REPLACE FUNCTION match_documents(
  query_embedding  VECTOR(1536),
  match_threshold  FLOAT   DEFAULT 0.7,
  match_count      INT     DEFAULT 5,
  filter_title     TEXT    DEFAULT NULL
)
RETURNS TABLE (
  id          UUID,
  title       TEXT,
  source      TEXT,
  chunk_index INTEGER,
  content     TEXT,
  metadata    JSONB,
  similarity  FLOAT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    d.id,
    d.title,
    d.source,
    d.chunk_index,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) AS similarity
  FROM documents d
  WHERE d.embedding IS NOT NULL
    AND 1 - (d.embedding <=> query_embedding) > match_threshold
    AND (filter_title IS NULL OR d.title = filter_title)
  ORDER BY d.embedding <=> query_embedding
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;
