// PM2 Ecosystem Configuration
// Manages telegram-relay (always-on) and scheduled routines (cron-based)

const path = require("path");
const CWD = process.env.RELAY_CWD || __dirname;
const BUN = process.env.BUN_PATH || "bun";
const HOME = process.env.HOME || "";
const RELAY_USER_DIR = process.env.RELAY_USER_DIR || process.env.RELAY_DIR || path.join(HOME, ".claude-relay");
const LOGS_DIR = process.env.PM2_LOG_DIR || path.join(RELAY_USER_DIR, "logs");
const ENV = {
  NODE_ENV: "production",
  PATH: process.env.PATH || "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
  HOME: HOME,
};

const QDRANT_BIN = process.env.QDRANT_BIN || HOME + "/.qdrant/bin/qdrant";
const MLX_BIN    = process.env.MLX_BIN    || HOME + "/.local/share/uv/tools/mlx-local/bin/mlx";
// Note: MLX generation server (port 8800) removed — replaced by LM Studio via ModelRegistry.
// MLX is now used exclusively for embeddings (mlx-embed, bge-m3, port 8801).

module.exports = {
  apps: [
    // ── Infrastructure: always-on ────────────────────────────────────────
    {
      name: "qdrant",
      script: QDRANT_BIN,
      interpreter: "none",
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      kill_timeout: 5000,
      args: "--config-path " + HOME + "/.qdrant/config.yaml",
      env: ENV,
      error_file: LOGS_DIR + "/qdrant-error.log",
      out_file: LOGS_DIR + "/qdrant-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },

    // ── Embedding server (mlx-local tool) ─────────────────────────────────────
    // mlx-embed: embeddings via bge-m3-mlx-fp16, port 8801
    // Text generation handled by LM Studio (or any OpenAI-compatible server) via ModelRegistry.
    {
      name: "mlx-embed",
      script: MLX_BIN,
      args: "serve-embed",
      interpreter: "none",
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: true,
      watch: false,
      kill_timeout: 5000,
      env: ENV,
      error_file: LOGS_DIR + "/mlx-embed-error.log",
      out_file: LOGS_DIR + "/mlx-embed-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },

    // ── Core: always-on ────────────────────────────────────────────────────
    {
      name: "telegram-relay",
      script: "relay-wrapper.js",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1500M",
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      env: ENV,
      error_file: LOGS_DIR + "/telegram-relay-error.log",
      out_file: LOGS_DIR + "/telegram-relay-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },

    // ── Daily briefings ────────────────────────────────────────────────────
    {
      name: "morning-summary",
      script: "routines/morning-summary.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 7 * * *",
      env: ENV,
      error_file: LOGS_DIR + "/morning-summary-error.log",
      out_file: LOGS_DIR + "/morning-summary-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "night-summary",
      script: "routines/night-summary.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 23 * * *",
      env: ENV,
      error_file: LOGS_DIR + "/night-summary-error.log",
      out_file: LOGS_DIR + "/night-summary-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },

    // ── Periodic check-ins ─────────────────────────────────────────────────
    {
      name: "smart-checkin",
      script: "routines/smart-checkin.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "*/30 * * * *",
      env: ENV,
      error_file: LOGS_DIR + "/smart-checkin-error.log",
      out_file: LOGS_DIR + "/smart-checkin-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },

    // ── Health & maintenance ───────────────────────────────────────────────
    {
      name: "watchdog",
      script: "routines/watchdog.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 */2 * * *",
      env: ENV,
      error_file: LOGS_DIR + "/watchdog-error.log",
      out_file: LOGS_DIR + "/watchdog-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "orphan-gc",
      script: "routines/orphan-gc.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 * * * *",
      env: ENV,
      error_file: LOGS_DIR + "/orphan-gc-error.log",
      out_file: LOGS_DIR + "/orphan-gc-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "log-cleanup",
      script: "routines/log-cleanup.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 6 * * 1",
      env: ENV,
      error_file: LOGS_DIR + "/log-cleanup-error.log",
      out_file: LOGS_DIR + "/log-cleanup-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "memory-dedup-review",
      script: "routines/memory-dedup-review.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 16 * * 5",
      env: ENV,
      error_file: LOGS_DIR + "/memory-dedup-review-error.log",
      out_file: LOGS_DIR + "/memory-dedup-review-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "memory-cleanup",
      script: "routines/memory-cleanup.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 3 * * *",
      env: ENV,
      error_file: LOGS_DIR + "/memory-cleanup-error.log",
      out_file: LOGS_DIR + "/memory-cleanup-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },

    // ── Weekly / investment ────────────────────────────────────────────────
    {
      name: "weekly-etf",
      script: "routines/weekly-etf.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 7 * * *",
      env: ENV,
      error_file: LOGS_DIR + "/weekly-etf-error.log",
      out_file: LOGS_DIR + "/weekly-etf-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "etf-52week-screener",
      script: "routines/etf-52week-screener.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 7 * * *",
      env: ENV,
      error_file: LOGS_DIR + "/etf-52week-screener-error.log",
      out_file: LOGS_DIR + "/etf-52week-screener-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "weekly-retro",
      script: "routines/weekly-retro.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 9 * * 0",
      env: ENV,
      error_file: LOGS_DIR + "/weekly-retro-error.log",
      out_file: LOGS_DIR + "/weekly-retro-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
