// PM2 Ecosystem Configuration
// Generated by setup/configure-pm2.ts
// DO NOT EDIT MANUALLY - Run: bun run setup/configure-pm2.ts

module.exports = {
  apps: [
  {
    "name": "telegram-relay",
    "script": "relay-wrapper.js",
    "interpreter": "/Users/furi/.bun/bin/bun",
    "exec_mode": "fork",
    "cwd": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay",
    "instances": 1,
    "autorestart": true,
    "watch": false,
    "max_memory_restart": "500M",
    "env": {
      "NODE_ENV": "production",
      "PATH": "/Users/furi/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "HOME": "/Users/furi",
      "CLAUDECODE": ""
    },
    "error_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/telegram-relay.error.log",
    "out_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/telegram-relay.log",
    "log_date_format": "YYYY-MM-DD HH:mm:ss Z"
  },
  {
    "name": "smart-checkin",
    "script": "examples/smart-checkin.ts",
    "interpreter": "/Users/furi/.bun/bin/bun",
    "exec_mode": "fork",
    "cwd": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay",
    "instances": 1,
    "autorestart": false,
    "watch": false,
    "max_memory_restart": "500M",
    "env": {
      "NODE_ENV": "production",
      "PATH": "/Users/furi/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "HOME": "/Users/furi",
      "CLAUDECODE": ""
    },
    "error_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/smart-checkin.error.log",
    "out_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/smart-checkin.log",
    "log_date_format": "YYYY-MM-DD HH:mm:ss Z",
    "cron_restart": "*/30 * * * *"
  },
  {
    "name": "morning-briefing",
    "script": "examples/morning-briefing-etf.ts",
    "interpreter": "/Users/furi/.bun/bin/bun",
    "exec_mode": "fork",
    "cwd": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay",
    "instances": 1,
    "autorestart": false,
    "watch": false,
    "max_memory_restart": "500M",
    "env": {
      "NODE_ENV": "production",
      "PATH": "/Users/furi/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "HOME": "/Users/furi",
      "CLAUDECODE": ""
    },
    "error_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/morning-briefing.error.log",
    "out_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/morning-briefing.log",
    "log_date_format": "YYYY-MM-DD HH:mm:ss Z",
    "cron_restart": "0 7 * * *"
  },
  {
    "name": "night-summary",
    "script": "examples/night-summary.ts",
    "interpreter": "/Users/furi/.bun/bin/bun",
    "exec_mode": "fork",
    "cwd": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay",
    "instances": 1,
    "autorestart": false,
    "watch": false,
    "max_memory_restart": "500M",
    "env": {
      "NODE_ENV": "production",
      "PATH": "/Users/furi/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "HOME": "/Users/furi",
      "CLAUDECODE": ""
    },
    "error_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/night-summary.error.log",
    "out_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/night-summary.log",
    "log_date_format": "YYYY-MM-DD HH:mm:ss Z",
    "cron_restart": "0 23 * * *"
  },
  {
    "name": "watchdog",
    "script": "setup/watchdog.ts",
    "interpreter": "/Users/furi/.bun/bin/bun",
    "exec_mode": "fork",
    "cwd": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay",
    "instances": 1,
    "autorestart": false,
    "watch": false,
    "max_memory_restart": "500M",
    "env": {
      "NODE_ENV": "production",
      "PATH": "/Users/furi/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      "HOME": "/Users/furi",
      "CLAUDECODE": ""
    },
    "error_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/watchdog.error.log",
    "out_file": "/Users/furi/Documents/WorkInGovTech/01_Projects/Tools/claude-telegram-relay/logs/watchdog.log",
    "log_date_format": "YYYY-MM-DD HH:mm:ss Z",
    "cron_restart": "15 0,6,8,12,18,23 * * *"
  }
]
};
