// PM2 Ecosystem Configuration
// Manages telegram-relay (always-on) and scheduled routines (cron-based)

const CWD = process.env.RELAY_CWD || __dirname;
const BUN = process.env.BUN_PATH || "bun";
const ENV = {
  NODE_ENV: "production",
  PATH: process.env.PATH || "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
  HOME: process.env.HOME || "",
};

module.exports = {
  apps: [
    {
      name: "telegram-relay",
      script: "relay-wrapper.js",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1500M",
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 15000,
      env: ENV,
      error_file: CWD + "/logs/telegram-relay-error.log",
      out_file: CWD + "/logs/telegram-relay.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "enhanced-morning-summary",
      script: "routines/enhanced-morning-summary.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 7 * * *",
      env: ENV,
      error_file: CWD + "/logs/enhanced-morning-summary-error.log",
      out_file: CWD + "/logs/enhanced-morning-summary.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "smart-checkin",
      script: "routines/smart-checkin.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "*/30 * * * *",
      env: ENV,
      error_file: CWD + "/logs/smart-checkin-error.log",
      out_file: CWD + "/logs/smart-checkin.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "night-summary",
      script: "routines/night-summary.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 23 * * *",
      env: ENV,
      error_file: CWD + "/logs/night-summary-error.log",
      out_file: CWD + "/logs/night-summary.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "weekly-etf",
      script: "routines/weekly-etf.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 17 * * 5",
      env: ENV,
      error_file: CWD + "/logs/weekly-etf-error.log",
      out_file: CWD + "/logs/weekly-etf.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "watchdog",
      script: "routines/watchdog.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 */2 * * *",
      env: ENV,
      error_file: CWD + "/logs/watchdog-error.log",
      out_file: CWD + "/logs/watchdog.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "memory-cleanup",
      script: "routines/memory-cleanup.ts",
      interpreter: BUN,
      exec_mode: "fork",
      cwd: CWD,
      instances: 1,
      autorestart: false,
      watch: false,
      cron_restart: "0 3 * * *",
      env: ENV,
      error_file: CWD + "/logs/memory-cleanup-error.log",
      out_file: CWD + "/logs/memory-cleanup.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],
};
