import { describe, test, expect, mock, beforeEach } from "bun:test";

// Mock callRoutineModel before importing the module under test
const mockGenerate = mock(() => Promise.resolve("AWS Lambda cost optimization"));
mock.module("../routines/routineModel.ts", () => ({
  callRoutineModel: mockGenerate,
}));

const { generateTopic } = await import("./topicGenerator.ts");

describe("generateTopic", () => {
  beforeEach(() => {
    mockGenerate.mockReset();
    mockGenerate.mockResolvedValue("AWS Lambda cost optimization");
  });

  test("returns ≤ 7 words for normal content (mock model)", async () => {
    const content = "I need to optimize my AWS Lambda functions for cost. Currently spending $500/month on Lambda invocations across 3 regions.";
    const result = await generateTopic(content);

    expect(mockGenerate).toHaveBeenCalledTimes(1);
    expect(result).toBe("AWS Lambda cost optimization");
    expect(result.split(/\s+/).length).toBeLessThanOrEqual(7);
  });

  test("returns first 50 chars trimmed for short content without calling model", async () => {
    const content = "Hello world";
    const result = await generateTopic(content);

    expect(mockGenerate).not.toHaveBeenCalled();
    expect(result).toBe("Hello world");
  });

  test("returns first 50 chars for content exactly at boundary (49 chars)", async () => {
    const content = "A".repeat(49);
    const result = await generateTopic(content);

    expect(mockGenerate).not.toHaveBeenCalled();
    expect(result).toBe(content);
  });

  test("calls model for content at 50 chars", async () => {
    const content = "A".repeat(50);
    await generateTopic(content);
    expect(mockGenerate).toHaveBeenCalledTimes(1);
  });

  test("returns first 60 chars fallback on model error", async () => {
    mockGenerate.mockRejectedValue(new Error("timeout"));
    const content = "This is a longer message that should trigger a model call but it will fail so we get the 60 char fallback.";
    const result = await generateTopic(content);

    expect(result).toBe(content.slice(0, 60).trim());
  });

  test("returns first 60 chars fallback when model returns too many words", async () => {
    mockGenerate.mockResolvedValue("This is way too many words for a topic label that should be short but is not");
    const content = "Some longer content that needs a topic label generated by the LLM model for indexing purposes.";
    const result = await generateTopic(content);

    // 15 words > 10 word limit, so fallback
    expect(result).toBe(content.slice(0, 60).trim());
  });

  test("strips surrounding quotes from model response", async () => {
    mockGenerate.mockResolvedValue('"AWS cost optimization"');
    const content = "I want to reduce my AWS bill by optimizing Lambda and S3 usage across multiple regions.";
    const result = await generateTopic(content);

    expect(result).toBe("AWS cost optimization");
  });
});
